env: qa
namespace: example-qa

image:
  extraEnv:
    KEKUS: PEKUS

config:
  livenessProbe:
    initialDelaySeconds: 40
  readinessProbe:
    initialDelaySeconds: 40
  resources:
    requests:
      memory: "300Mi"
      cpu: "50m"
    limits:
      memory: "700Mi"
      cpu: "100m"
