---
apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: demo
spec:
  environments:
    stage:
      defaultNamespace: stage
      server: https://localhost:8443
    prod:
      defaultNamespace: prod
      server: https://localhost:443
  vars:
    external:
      - name: cm-value
        default: def
    computed:
      - name: helm
        code: |
          {
            command: './script.sh',
            args: [ "-s", "../vendor/example", "-v", "0.1.0" ],
            env: {},
            stdin: '',
          }
  dataSources:
    - exec://helm?configVar=helm
