---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.annotations" . | indent 4 }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    {{- range $key, $value := .Values.istio.ports }}
    - name: {{ $key }}
      protocol: TCP
      port: {{ $value }}
      targetPort: {{ $value }}
    {{- end }}
